# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation, advertising
# materials, and other materials related to such distribution.
# 
# THIS SOFTWARE IS PROVIDED AS IS AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#
# # This file was automaticaly generated by GenSeN
# It express the node's position
#
#
# Number of Nodes	: 32
# Simulation Area	: 60 x 100 
# Deployment Strategy	: Clif
# Seed           	: 825079

$node_(0) set X_ 9.408000 
$node_(0) set Y_ 46.969000 
$node_(1) set X_ 42.042000 
$node_(1) set Y_ 68.959000 
$node_(2) set X_ 19.658000 
$node_(2) set Y_ 63.970000 
$node_(3) set X_ 10.155000 
$node_(3) set Y_ 65.931000 
$node_(4) set X_ 43.881000 
$node_(4) set Y_ 65.284000 
$node_(5) set X_ 26.393000 
$node_(5) set Y_ 52.801000 
$node_(6) set X_ 10.902000 
$node_(6) set Y_ 57.935000 
$node_(7) set X_ 36.151000 
$node_(7) set Y_ 52.372000 
$node_(8) set X_ 22.753000 
$node_(8) set Y_ 95.671000 
$node_(9) set X_ 18.002000 
$node_(9) set Y_ 20.744000 
$node_(10) set X_ 42.170000 
$node_(10) set Y_ 96.510000 
$node_(11) set X_ 38.500000 
$node_(11) set Y_ 3.596000 
$node_(12) set X_ 15.022000 
$node_(12) set Y_ 5.962000 
$node_(13) set X_ 58.998000 
$node_(13) set Y_ 20.095000 
$node_(14) set X_ 41.521000 
$node_(14) set Y_ 9.631000 
$node_(15) set X_ 25.849000 
$node_(15) set Y_ 2.947000 
$node_(16) set X_ 52.537000 
$node_(16) set Y_ 54.485000 
$node_(17) set X_ 39.446000 
$node_(17) set Y_ 6.958000 
$node_(18) set X_ 23.362000 
$node_(18) set Y_ 29.816000 
$node_(19) set X_ 6.845000 
$node_(19) set Y_ 2.298000 
$node_(20) set X_ 43.724000 
$node_(20) set Y_ 47.967000 
$node_(21) set X_ 27.343000 
$node_(21) set Y_ 43.797000 
$node_(22) set X_ 7.592000 
$node_(22) set Y_ 39.992000 
$node_(23) set X_ 39.194000 
$node_(23) set Y_ 26.649000 
$node_(24) set X_ 19.443000 
$node_(24) set Y_ 52.686000 
$node_(25) set X_ 14.692000 
$node_(25) set Y_ 43.148000 
$node_(26) set X_ 39.574000 
$node_(26) set Y_ 70.214000 
$node_(27) set X_ 26.000000 
$node_(27) set Y_ 58.950000 
$node_(28) set X_ 0.439000 
$node_(28) set Y_ 63.437000 
$node_(29) set X_ 37.499000 
$node_(29) set Y_ 62.619000 
$node_(30) set X_ 27.290000 
$node_(30) set Y_ 92.766000 
$node_(31) set X_ 7.539000 
$node_(31) set Y_ 87.888000 




PRINTING FOUNDINGS...
 1 3 3 1
 3 2 4 2
 3 2 5 1
 1 0 1 0
