# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation, advertising
# materials, and other materials related to such distribution.
# 
# THIS SOFTWARE IS PROVIDED AS IS AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#
# # This file was automaticaly generated by GenSeN
# It express the node's position
#
#
# Number of Nodes	: 32
# Simulation Area	: 60 x 100 
# Deployment Strategy	: Clif
# Seed           	: 582428

$node_(0) set X_ 15.234000 
$node_(0) set Y_ 2.447000 
$node_(1) set X_ 53.675000 
$node_(1) set Y_ 28.525000 
$node_(2) set X_ 40.101000 
$node_(2) set Y_ 22.183000 
$node_(3) set X_ 20.174000 
$node_(3) set Y_ 32.194000 
$node_(4) set X_ 10.251000 
$node_(4) set Y_ 1.600000 
$node_(5) set X_ 38.026000 
$node_(5) set Y_ 28.943000 
$node_(6) set X_ 22.102000 
$node_(6) set Y_ 29.521000 
$node_(7) set X_ 2.351000 
$node_(7) set Y_ 9.525000 
$node_(8) set X_ 42.600000 
$node_(8) set Y_ 25.951000 
$node_(9) set X_ 22.377000 
$node_(9) set Y_ 26.848000 
$node_(10) set X_ 3.098000 
$node_(10) set Y_ 36.859000 
$node_(11) set X_ 40.229000 
$node_(11) set Y_ 55.517000 
$node_(12) set X_ 23.596000 
$node_(12) set Y_ 50.302000 
$node_(13) set X_ 10.198000 
$node_(13) set Y_ 66.728000 
$node_(14) set X_ 38.154000 
$node_(14) set Y_ 66.078000 
$node_(15) set X_ 15.696000 
$node_(15) set Y_ 62.855000 
$node_(16) set X_ 10.945000 
$node_(16) set Y_ 73.211000 
$node_(17) set X_ 36.079000 
$node_(17) set Y_ 66.524000 
$node_(18) set X_ 29.504000 
$node_(18) set Y_ 96.494000 
$node_(19) set X_ 26.692000 
$node_(19) set Y_ 23.931000 
$node_(20) set X_ 36.941000 
$node_(20) set Y_ 84.652000 
$node_(21) set X_ 35.430000 
$node_(21) set Y_ 23.862000 
$node_(22) set X_ 18.792000 
$node_(22) set Y_ 6.856000 
$node_(23) set X_ 53.282000 
$node_(23) set Y_ 2.531000 
$node_(24) set X_ 39.290000 
$node_(24) set Y_ 23.355000 
$node_(25) set X_ 19.781000 
$node_(25) set Y_ 30.393000 
$node_(26) set X_ 49.858000 
$node_(26) set Y_ 51.529000 
$node_(27) set X_ 37.633000 
$node_(27) set Y_ 9.869000 
$node_(28) set X_ 20.286000 
$node_(28) set Y_ 30.569000 
$node_(29) set X_ 6.888000 
$node_(29) set Y_ 14.132000 
$node_(30) set X_ 35.558000 
$node_(30) set Y_ 30.078000 
$node_(31) set X_ 21.984000 
$node_(31) set Y_ 40.065000 




PRINTING FOUNDINGS...
 3 1 2 0
 3 6 2 1
 4 3 3 1
 1 1 1 0
