# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation, advertising
# materials, and other materials related to such distribution.
# 
# THIS SOFTWARE IS PROVIDED AS IS AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#
# # This file was automaticaly generated by GenSeN
# It express the node's position
#
#
# Number of Nodes	: 10
# Simulation Area	: 60 x 100 
# Deployment Strategy	: Clif
# Seed           	: 458124

$node_(0) set X_ 32.246000 
$node_(0) set Y_ 81.284000 
$node_(1) set X_ 39.905000 
$node_(1) set Y_ 13.958000 
$node_(2) set X_ 20.915000 
$node_(2) set Y_ 7.302000 
$node_(3) set X_ 49.944000 
$node_(3) set Y_ 49.233000 
$node_(4) set X_ 32.005000 
$node_(4) set Y_ 21.883000 
$node_(5) set X_ 27.254000 
$node_(5) set Y_ 38.242000 
$node_(6) set X_ 52.503000 
$node_(6) set Y_ 79.735000 
$node_(7) set X_ 31.161000 
$node_(7) set Y_ 41.911000 
$node_(8) set X_ 26.234000 
$node_(8) set Y_ 27.664000 
$node_(9) set X_ 8.250000 
$node_(9) set Y_ 12.660000 




PRINTING FOUNDINGS...
 1 0 0 0
 1 2 0 0
 2 1 0 1
 0 1 0 1
