# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation, advertising
# materials, and other materials related to such distribution.
# 
# THIS SOFTWARE IS PROVIDED AS IS AND WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#
# # This file was automaticaly generated by GenSeN
# It express the node's position
#
#
# Number of Nodes	: 32
# Simulation Area	: 60 x 100 
# Deployment Strategy	: Clif
# Seed           	: 668378

$node_(0) set X_ 11.470000 
$node_(0) set Y_ 30.831000 
$node_(1) set X_ 43.072000 
$node_(1) set Y_ 47.257000 
$node_(2) set X_ 23.321000 
$node_(2) set Y_ 69.624000 
$node_(3) set X_ 3.570000 
$node_(3) set Y_ 30.109000 
$node_(4) set X_ 40.182000 
$node_(4) set Y_ 73.736000 
$node_(5) set X_ 26.608000 
$node_(5) set Y_ 51.223000 
$node_(6) set X_ 4.317000 
$node_(6) set Y_ 64.038000 
$node_(7) set X_ 44.460000 
$node_(7) set Y_ 54.892000 
$node_(8) set X_ 15.886000 
$node_(8) set Y_ 89.903000 
$node_(9) set X_ 26.417000 
$node_(9) set Y_ 20.959000 
$node_(10) set X_ 42.385000 
$node_(10) set Y_ 93.572000 
$node_(11) set X_ 43.811000 
$node_(11) set Y_ 12.230000 
$node_(12) set X_ 15.237000 
$node_(12) set Y_ 22.241000 
$node_(13) set X_ 37.413000 
$node_(13) set Y_ 95.749000 
$node_(14) set X_ 41.736000 
$node_(14) set Y_ 0.910000 
$node_(15) set X_ 27.911000 
$node_(15) set Y_ 3.162000 
$node_(16) set X_ 59.513000 
$node_(16) set Y_ 44.588000 
$node_(17) set X_ 39.762000 
$node_(17) set Y_ 19.661000 
$node_(18) set X_ 20.011000 
$node_(18) set Y_ 41.895000 
$node_(19) set X_ 0.260000 
$node_(19) set Y_ 2.513000 
$node_(20) set X_ 43.939000 
$node_(20) set Y_ 45.564000 
$node_(21) set X_ 24.012000 
$node_(21) set Y_ 37.784000 
$node_(22) set X_ 1.007000 
$node_(22) set Y_ 10.438000 
$node_(23) set X_ 41.864000 
$node_(23) set Y_ 40.876000 
$node_(24) set X_ 27.858000 
$node_(24) set Y_ 43.290000 
$node_(25) set X_ 8.107000 
$node_(25) set Y_ 43.363000 
$node_(26) set X_ 39.789000 
$node_(26) set Y_ 56.571000 
$node_(27) set X_ 26.215000 
$node_(27) set Y_ 50.362000 
$node_(28) set X_ 8.854000 
$node_(28) set Y_ 60.240000 
$node_(29) set X_ 34.103000 
$node_(29) set Y_ 67.714000 
$node_(30) set X_ 29.352000 
$node_(30) set Y_ 63.909000 
$node_(31) set X_ 0.954000 
$node_(31) set Y_ 58.210000 




PRINTING FOUNDINGS...
 2 3 3 0
 3 3 4 1
 3 3 4 2
 0 1 0 0
